export const tagsOptions = [
    { value: 'Android', label: 'Android' },
    { value: 'iOS', label: 'iOS' },
    { value: 'macOS', label: 'macOS' },
    { value: 'Windows', label: 'Windows' },
    { value: 'Браузеры', label: 'Браузеры' },
    { value: 'Вдохновение', label: 'Вдохновение' },
    { value: 'Веб-сервисы', label: 'Веб-сервисы' },
    { value: 'Видео', label: 'Видео' },
    { value: 'Выживание', label: 'Выживание' },
    { value: 'Еда', label: 'Еда' },
    { value: 'Жизнь', label: 'Жизнь' },
    { value: 'Здоровье', label: 'Здоровье' },
    { value: 'Игры', label: 'Игры' },
    { value: 'Интернет', label: 'Интернет' },
    { value: 'Кино', label: 'Кино' },
    { value: 'Книги', label: 'Книги' },
    { value: 'Колонка', label: 'Колонка' },
    { value: 'Ликбез', label: 'Ликбез' },
    { value: 'Мотивация', label: 'Мотивация' },
    { value: 'Музыка', label: 'Музыка' },
    { value: 'Новости', label: 'Новости' },
    { value: 'Образование', label: 'Образование' },
    { value: 'Ответы', label: 'Ответы' },
    { value: 'Отдых', label: 'Отдых' },
    { value: 'Отношения', label: 'Отношения' },
    { value: 'Подкасты', label: 'Подкасты' },
    { value: 'Покупки', label: 'Покупки' },
    { value: 'Право', label: 'Право' },
    { value: 'Праздники', label: 'Праздники' },
    { value: 'Пресс-релизы', label: 'Пресс-релизы' },
    { value: 'Продуктивность', label: 'Продуктивность' },
    { value: 'Путешествия', label: 'Путешествия' },
    { value: 'Работа и учёба', label: 'Работа и учёба' },
    { value: 'Рабочие места', label: 'Рабочие места' },
    { value: 'Редакция', label: 'Редакция' },
    { value: 'Своё дело', label: 'Своё дело' },
    { value: 'Сделай сам', label: 'Сделай сам' },
    { value: 'Секс', label: 'Секс' },
    { value: 'Советы', label: 'Советы' },
    { value: 'Спорт и фитнес', label: 'Спорт и фитнес' },
    { value: 'Стать богатым', label: 'Стать богатым' },
    { value: 'Тесты', label: 'Тесты' },
    { value: 'Технологии', label: 'Технологии' },
    { value: 'Устройства', label: 'Устройства' },
    { value: 'Фото', label: 'Фото' },
]